env: "working" #develop, working
log_path: "./logs"
shutdown_timeout: 5s

core_settings:
  storage: "./data"
  bucket_size: 800
  friendly: true

websocket_connector:
  enable: true
  address: "0.0.0.0"
  port: "8080"
  buffer_size:
    read: 1024
    write: 1024

rest_connector:
  enable: true
  address: "0.0.0.0"
  port: "31337"

grpc_connector:
  enable: true
  address: "0.0.0.0"
  port: "3137"

web_server:
  enable: true
  address: "0.0.0.0"
  port: "80"
